# Generated by Django 3.0.4 on 2020-03-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200305_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
